### PR TITLE
MLOPS-73 | kubeflow init

### PR DESCRIPTION
**Pull request by szczeles**

### CODE REVIEW

**Review by em-pe — CHANGES_REQUESTED** [review]
Please mention this change in CHANGELOG.md, the rest looks fine.

**Comment by szczeles** [comment]
Changelog entry added + sample file provided

**Comment by szczeles** [comment]
Oh, wait, I will copy the file into README md

**Review by em-pe — APPROVED** [review]

**Comment by em-pe** [comment]
Ignore failing coverage checks for now. I'll add CLI coverage and then restore them. As an admin you should be able to merge despite failing checks

**Pull request merged**
